import { computeFreshness } from "@/lib/education/freshness";
import { cn } from "@/lib/utils";
import type { ArticleGovernance } from "@/lib/sanity";
import type { PublishingRecommendation } from "@/lib/types";
import { formatPublishedDate } from "@/utils/date";

const RECOMMENDATION_LABELS: Record<PublishingRecommendation, string> = {
  ready: "Ready to Publish",
  "needs-attention": "Needs Attention",
};

interface GovernanceSidebarProps {
  /** Null/absent on documents published before governance existed. */
  governance?: ArticleGovernance | null;
  publishedAt: string;
}

function GovernanceRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="grid gap-0.5">
      <dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
        {label}
      </dt>
      <dd className="text-sm text-foreground">{value}</dd>
    </div>
  );
}

/**
 * Content Governance panel for an article page: review outcome,
 * freshness, and provenance of the Knowledge Asset. Renders gracefully
 * for documents published before governance fields existed.
 */
export function GovernanceSidebar({
  governance,
  publishedAt,
}: GovernanceSidebarProps) {
  const freshness = computeFreshness({
    publishedAt,
    lastReviewedAt: governance?.lastReviewedAt,
  });

  return (
    <aside
      aria-label="Content governance"
      className="h-fit rounded-lg border bg-card p-6 lg:sticky lg:top-24"
    >
      <h2 className="mb-5 font-serif text-lg font-normal tracking-tight">
        Content Governance
      </h2>
      <dl className="grid gap-4">
        <GovernanceRow label="Status" value="Published" />
        {typeof governance?.reviewScore === "number" && (
          <GovernanceRow
            label="Review score"
            value={`${governance.reviewScore} / 100`}
          />
        )}
        {governance?.publishingRecommendation !== undefined &&
          governance.publishingRecommendation in RECOMMENDATION_LABELS && (
            <GovernanceRow
              label="Review outcome"
              value={
                RECOMMENDATION_LABELS[governance.publishingRecommendation]
              }
            />
          )}
        {freshness !== null && (
          <div className="grid gap-1">
            <dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
              Freshness
            </dt>
            <dd className="grid gap-1.5">
              <span className="text-sm text-foreground">
                {freshness.label} — {freshness.score} / 100
              </span>
              <span
                aria-hidden="true"
                className="block h-1 w-full overflow-hidden rounded-full bg-border"
              >
                <span
                  className={cn(
                    "block h-full rounded-full bg-foreground/70 transition-all",
                  )}
                  style={{ width: `${freshness.score}%` }}
                />
              </span>
            </dd>
          </div>
        )}
        {governance?.generatedBy && (
          <GovernanceRow label="Generated by" value={governance.generatedBy} />
        )}
        {governance?.reviewAgentVersion && (
          <GovernanceRow
            label="Review agent"
            value={governance.reviewAgentVersion}
          />
        )}
        {governance?.documentationVersion && (
          <GovernanceRow
            label="Documentation version"
            value={governance.documentationVersion}
          />
        )}
        {governance?.lastReviewedAt && (
          <GovernanceRow
            label="Last reviewed"
            value={formatPublishedDate(governance.lastReviewedAt)}
          />
        )}
        <GovernanceRow
          label="Published"
          value={formatPublishedDate(publishedAt)}
        />
      </dl>
    </aside>
  );
}
