import ReactMarkdown, { type Components } from "react-markdown";
import remarkGfm from "remark-gfm";

import { cn } from "@/lib/utils";

/**
 * Presentation-grade Markdown rendering for generated articles — polished,
 * executive-ready prose rather than raw Markdown. Supports GitHub-Flavored
 * Markdown (tables, task lists, autolinks, strikethrough) and every common
 * construct: headings, bold/italic, inline and fenced code, ordered and
 * unordered lists, blockquotes, links, rules, and images.
 *
 * Article headings sit under the page/card title, so Markdown `#` renders
 * as a visual `<h2>`, `##` as `<h3>`, and so on — keeping the document
 * outline correct. Raw HTML in the source is intentionally not rendered.
 */
const COMPONENTS: Components = {
  h1: ({ children }) => (
    <h2 className="font-serif text-2xl font-normal tracking-tight text-foreground">
      {children}
    </h2>
  ),
  h2: ({ children }) => (
    <h3 className="text-xl font-medium tracking-tight text-foreground">
      {children}
    </h3>
  ),
  h3: ({ children }) => (
    <h4 className="text-lg font-medium text-foreground">{children}</h4>
  ),
  h4: ({ children }) => (
    <h5 className="text-base font-semibold text-foreground">{children}</h5>
  ),
  h5: ({ children }) => (
    <h6 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">
      {children}
    </h6>
  ),
  h6: ({ children }) => (
    <h6 className="text-sm font-medium text-foreground">{children}</h6>
  ),
  p: ({ children }) => (
    <p className="leading-7 text-muted-foreground">{children}</p>
  ),
  strong: ({ children }) => (
    <strong className="font-semibold text-foreground">{children}</strong>
  ),
  em: ({ children }) => <em className="italic">{children}</em>,
  ul: ({ children }) => (
    <ul className="grid list-disc gap-2 pl-5 text-muted-foreground marker:text-muted-foreground/50">
      {children}
    </ul>
  ),
  ol: ({ children }) => (
    <ol className="grid list-decimal gap-2 pl-5 text-muted-foreground marker:text-muted-foreground/60">
      {children}
    </ol>
  ),
  li: ({ children }) => <li className="pl-1 leading-7">{children}</li>,
  a: ({ href, children }) => {
    const external = typeof href === "string" && /^https?:\/\//.test(href);
    return (
      <a
        href={href}
        className="font-medium text-primary underline underline-offset-4 transition-opacity hover:opacity-80"
        {...(external
          ? { target: "_blank", rel: "noopener noreferrer" }
          : {})}
      >
        {children}
      </a>
    );
  },
  blockquote: ({ children }) => (
    <blockquote className="border-l-2 border-border pl-4 italic text-muted-foreground">
      {children}
    </blockquote>
  ),
  hr: () => <hr className="border-border" />,
  code: ({ className, children }) => {
    // Fenced blocks carry a `language-*` class; bare inline code does not.
    const isBlock = /language-/.test(className ?? "");
    if (isBlock) {
      return <code className="font-mono text-sm">{children}</code>;
    }
    return (
      <code className="rounded bg-muted px-1.5 py-0.5 font-mono text-[0.85em] text-foreground">
        {children}
      </code>
    );
  },
  pre: ({ children }) => (
    <pre className="overflow-x-auto rounded-lg border border-border bg-muted p-4 text-sm text-foreground">
      {children}
    </pre>
  ),
  table: ({ children }) => (
    <div className="overflow-x-auto rounded-lg border border-border">
      <table className="w-full border-collapse text-sm">{children}</table>
    </div>
  ),
  thead: ({ children }) => <thead className="bg-muted/50">{children}</thead>,
  th: ({ children }) => (
    <th className="border-b border-border px-3 py-2 text-left font-medium text-foreground">
      {children}
    </th>
  ),
  td: ({ children }) => (
    <td className="border-b border-border px-3 py-2 text-muted-foreground">
      {children}
    </td>
  ),
  img: ({ src, alt }) => (
    // Article images come from arbitrary Markdown URLs, so next/image's
    // configured-domains model doesn't apply — a plain <img> is correct here.
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={typeof src === "string" ? src : undefined}
      alt={alt ?? ""}
      className="max-w-full rounded-lg border border-border"
    />
  ),
};

interface MarkdownProps {
  /** The raw Markdown source (as generated by the AI / stored in Sanity). */
  children: string;
  className?: string;
}

/** Renders Markdown as polished, executive-ready prose. */
export function Markdown({ children, className }: MarkdownProps) {
  return (
    <div className={cn("grid gap-4 text-[0.95rem]", className)}>
      <ReactMarkdown remarkPlugins={[remarkGfm]} components={COMPONENTS}>
        {children}
      </ReactMarkdown>
    </div>
  );
}
